// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fade(c,a,b){var e=jQuery;var d=e("ul",b);var f={position:"absolute",left:0,top:0,width:"100%",height:"100%"};this.go=function(g,h){var i=e(a.get(g)).clone().css(f).hide().appendTo(b);if(!c.noCross){var j=e(a.get(h)).clone().css(f).appendTo(b);d.hide();j.fadeOut(c.duration,function(){j.remove()})}i.fadeIn(c.duration,function(){d.css({left:-g+"00%"}).show();i.remove()});return g}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"fade",prev:"prev",next:"next",duration:20*100,delay:35*100,width:916,height:320,autoPlay:true,playPause:true,stopOnHover:true,loop:false,bullets:true,caption:false,captionEffect:"slide",controls:true,onBeforeStep:0,images:[{src:"./slide_general.jpg",title:"slide_general",href:"contact.php"},{src:"./slideambition.jpg",title:"slide-ambition",href:"https://www.facebook.com/RoadmasterDriversSchool",target:"_blank"},{src:"./slide_military.jpg",title:"Veterans Training",href:"veteran-cdl-training.php"},{src:"./slide_hiring.jpg",title:"slide_hiring",href:"http://www.roadmaster.com/blog/work-for-roadmaster-cdl-instructor-job-openings-in-7-different-cities/",target:"_blank"}]});