<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="canonical" href="default.php" />
<link href='http://fonts.googleapis.com/css?family=Kaushan+Script|Shadows+Into+Light+Two' rel='stylesheet' type='text/css'>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="DESCRIPTION" content="Roadmaster is a hands on truck driving school & CDL training center that provides complete truck driver training & CDL Class A license preparation.">
<meta name="msvalidate.01" content="4E7106809F202E6C88FEF26B032D8B98" />
<?php include("/inc/head.inc"); ?>
<?php
// Include WordPress 
define('WP_USE_THEMES', false);
include('/blog/wp-load.php');
query_posts('showposts=4'); 
?>

 		<script type="text/javascript" src="/inc/js/swfobject.js"></script>
		<script type="text/javascript">
		swfobject.registerObject("myId", "9.0.0", "expressInstall.swf");
		</script>
 
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="slider/engine1/style.css" />
	<script type="text/javascript" src="slider/engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
	
<title>CDL Training and Truck Driving School - Roadmaster</title>
</head>

<body>
<div id="wrapper">

<!-- Top Menu -->
<div id="menu">
	<?php include("/inc/menu.inc"); ?>
</div>
<!-- End Top Menu -->

<!-- Slider -->
<div id="hpHeaderNew">

<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1" style="z-index:0;">
	<div class="ws_images"><ul>
<li><a href="contact.php"><img src="slider/data1/images/slide_general.jpg" alt="slide_general" title="slide_general" id="wows1_0"/></a></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="slider/data1/images/slide_general.jpg" title="slide_general"><img src="slider/data1/tooltips/slide_general.jpg" alt="slide_general"/>1</a>
<a href="slider/data1/images/slideambition.jpg" title="slide-ambition">2</a>
<a href="slider/data1/images/slide_military.jpg" title="Veterans Training">3</a>
<a href="slider/data1/images/slide_hiring.jpg" title="slide_hiring">4</a>
</div></div>
<!-- Generated by WOWSlider.com v4.7 -->

<!-- Generated by WOWSlider.com v4.7 -->
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="slider/engine1/wowslider.js"></script>
	<script type="text/javascript" src="slider/engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
             
</div>
<!-- Slider End -->



<!-- Bottom Bar Begin (Short Form, Middle Text, Location Map) -->
<div id="bottomBar">
	<div id="shortForm">
   	 <!-- Begin Short Form Validation Include -->

<style type="text/css">
label { width: 10em; float: left; font-size:11px;}
label.error { float: none; color: red; padding-left: .5em; vertical-align: top; }
</style>
  <script>
  $(document).ready(function(){
    $("#quickLeadForm").validate({
		  rules: {
   			 ZipCode: {
     			 required: true,
     			 digits: true,
				 maxlength: 5,
				 minlength: 5
   				  },
			
			Phone: {
  			     required: true,
				 minlength: 10,
  			}
  			  }		 		 
});
		 });
  </script>
  
<!-- End Short Form Validation Include -->
<div id="quickformHP">

                <form action="/common/form/leadform.php" method="post" id="quickLeadForm">
                
                <input type="hidden" name="LeadType" value="RDS"/>
                <input type="hidden" name="SuccessPage" value="/confirmationShort.php"/>
                <input type="hidden" name="ErrorPage" value="/error.php"/>
                <input type="hidden" name="EmailOptIn" value="1"/>
                
                <div class="label">First Name</div><div class="input"><input name="FirstName" type="text" id="FirstName" size="14" class="required"/></div>
                <div class="label clear">Last Name</div><div class="input"><input name="LastName" type="text" id="LastName" size="14" class="required" /></div>
                <div class="label clear">Phone</div><div class="input"><input name="Phone" type="text" id="Phone" size="14" maxlength="14" class="required" /></div>
                <div class="label clear">E-Mail</div><div class="input"><input name="EmailAddress" type="text" id="EmailAddress" size="14" maxlength="40" class="required email"/></div>
                <div class="label clear">Zip Code</div><div class="input"><input name="ZipCode" type="text" id="ZipCode" size="10" maxlength="10" class="ZipCode"/></div>
                <!--<div class="labelFull clear"><input id="Checkbox1" checked type="checkbox" name="EmailOptIn"/><span style="font-size:10px;">Send me correspondence and/or texts (SMS)</span></div>-->
                <div class="submit clear"><input name="Submit" type="submit" value="Submit" /></div>
                <div class="disclaimer">By submitting this form you are expressly consenting to<br>our <a style="text-decoration:underline;" href="terms-of-use.php" target="_blank">Terms of Use</a> and that you may be contacted by a representative via telephone, email or SMS Text</div>
                
                </form>
</div>

    </div>
    
	<div id="bottomContent" style="padding-top:0px; margin-left:7px; padding-top:3px; width:285px;">
		<a href="http://roadmaster.deco-apparel.com/" target="_blank"><img src="images/storeGraphic.gif"></a>
		
	</div>

	<div id="bottomMap">
		<h3>Locations across the USA</h3>
		   <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="282" height="170" id="myFlashContent">
		   			<param name="movie" value="us.swf?data_file=rm.xml" />
		   			<param name="wmode" value="transparent" />
		   			<!--[if !IE]>-->
		   			<object type="application/x-shockwave-flash" data="us.swf?data_file=rm.xml" width="282" height="170">
		   				<param name="wmode" value="transparent" />
		   			<!--<![endif]-->
		   				<a href="truck_school_locations.php">
		   					<img alt="Truck Driver Training School Locations" src="/images/mapSmall.png" border="0">
		   				</a>
		   			<!--[if !IE]>-->
		   			</object>
		   			<!--<![endif]-->
		   		</object>
			
		   		<span style="text-align:center; font-size:11px;">Click a state to zoom in, then choose a school</span>
	</div>

</div> 
<!-- End Bottom Bar -->

<div id="hpContentWrapper2">
<img alt="Roadmaster Drivers School CDL Training" id="Image-Maps_6201201161544457" src="/images/hpBarSplit.jpg" width="917" height="45" border="0" usemap="#Image-Maps_6201201161544457" title="Roadmaster Drivers School" />
<map id="_Image-Maps_6201201161544457" name="Image-Maps_6201201161544457">
<area shape="rect" coords="0,0,447,50" href="/blog" alt="" title=""    />
</map>


<div id="hpContentLeft2">

<div class="wpEmbed">
<?php  while (have_posts()): the_post(); ?>
<h3 class="wpDate" style="color:#fff;"><?php the_date(); ?> - <?php the_category(); ?></h3>
<h2 class="wpTitle"><a class="wpTitleLink" style="color:white;" href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
<?php the_excerpt(); ?><a class="wpLink" href="<?php the_permalink(); ?>">Read more...</a>
<div class="wpBreak"><a href="blog"><img alt="View our truck driving blog" border="0" src="/images/viewBlog.png"></a></div>
<?php endwhile; ?>
</div>

</div> <!-- End HP Left -->

<div id="hpContentRight2" class="editable"><h1><strong>CDL Training</strong> and <strong>Truck Driving School</strong>,
<strong>Roadmaster Drivers School</strong> has locations across the United
States. Most trucking companies require the successful completion of the CDL
test and a Class A CDL commercial driver's license before driving a truck for
them. As a truck driving school, Roadmaster provides you with the CDL training
lessons you need to get either a Class A CDL or Class B CDL license to help you
start your professional truck driving career today!</h1>

<p>Roadmaster is dedicated to preparing individuals for a career <em>driving a
truck</em> to meet the fast growing need for qualified professional truck
drivers. By preparing students for a successful career through providing the
best possible state of the art training at our <em>CDL school</em>, Roadmaster
will work for the success of every student while building a reputation that
will ensure valuable future opportunities for graduates of Roadmaster. Our
mission will be enhanced and realized through strong community commitment and
upholding the value of every individual student who enrolls into a Roadmaster
truck driving school.</p>

<p><a href="http://www.truckline.com" target="_blank"><img alt=
"American Trucking Association" border="0" height="135" src="images/ata.jpg"
style="float: left; padding-right: 20px;" width="112" /></a><a href=
"http://www.careerpathtraining.com" target="_blank">Career Path Training
Corporation</a> opened the first Roadmaster Drivers School <em>truck driving
school</em> and <em>cdl training</em> center in Tampa, Florida in 1992.
Roadmaster quickly gained a national reputation in the trucking industry for
quality training of entry-level commercial truck drivers. Because truck drivers
with a Class A CDL license have the potential for employment in so many
different areas, a varied approach to safety conscious truck driver training is
needed. Roadmaster takes a hands-on approach to training drivers to get their
Class A CDL license.</p>

<p><a href="http://www.truckload.org" target="_blank"><img alt=
"Truckload Carriers Association" border="0" height="100" src="images/tca.jpg"
style="float: right; padding-left: 20px; padding-bottom: 10px;" width=
"100" /></a>Online CDL training schools do not provide you with the hands on
truck driver training that employers are looking for and that you need to start
driving a truck professionally. Roadmaster will teach you advanced truck
driving techniques such as skid avoidance and recovery as well as other
emergency actions. CDL training from Roadmaster makes you far more valuable in
the job market. When applying for truck driving jobs, hiring companies will
know that you have received the proper truck driving school training and are
ready to start your career as a professional over the road truck driver.</p>

<p>Roadmaster Drivers School provides you with Class A CDL &amp; Class B CDL
license training and truck driver training in as few as 3-4 weeks. With classes
forming weekly at our <a href="truck_school_locations.php">12 truck driving
schools from Florida to California</a>, there has never been a better time to
start your truck driving career. Roadmaster truck driving school offers FREE
job placement assistance after graduation. Tuition assistance is also available
for those who qualify. Today, most trucking companies may offer reimbursement
for truck driver training programs. Roadmaster is also Approved for Veterans
Training.</p>

<p><a href="http://www.cvta.org" target="_blank"><img alt=
"Commercial Vehicle Training Association" border="0" height="53" src=
"images/cvta.jpg" style=
"float: left; padding-right: 20px; padding-bottom: 20px;" width="125" /></a>All
truck driving school locations have administrative offices, spacious
classrooms, and computer labs. The schools maintain specially designed
field-driving courses where students practice backing, coupling, uncoupling,
docking and driving a truck. Roadmaster truck driving school provides equipment
for Commercial Driver Licensing (CDL) testing at all locations. Roadmaster owns
a fleet of late model tractor-trailers used exclusively for student training.
Get your truck driving career started today with a well equipped, hands-on cdl
training school with the reputation to back it up!</p>

<p><span class="disclaimer">* Course Length may vary by location.</span></p></div> <!-- End HP Right -->

<!-- Event Manager Listing -->
<div id="listingsHP">
	  <?php include("mm/mm-framed-hp.php"); ?>
</div>
<!-- Event Manager Listings End -->
<?php include("/inc/footer.inc"); ?>
</div> <!-- End Wrapper -->
</div>
<br><br>
<?php include("/inc/analytics.inc"); ?>
</body>
</html>