    <div id="carrierBar">
    	<img border="0" src="images/carrierBarLeftCap.jpg" />
        <a href="#"><img border="0" src="images/carrierBarLogo1.jpg" /></a>
        <a href="#"><img border="0" src="images/carrierBarLogo2.jpg" /></a>
        <a href="#"><img border="0" src="images/carrierBarLogo3.jpg" /></a>
        <a href="#"><img border="0" src="images/carrierBarLogo4.jpg" /></a>
        <a href="#"><img border="0" src="images/carrierBarLogo5.jpg" /></a>
    	<img border="0" src="images/carrierBarRightCap.jpg" />
	</div>