<div style="clear:both; padding-left:70px;">

<div style="float:left;"><g:plusone size="medium"></g:plusone></div>
    
    
<div style="float:left"><a href="http://twitter.com/share" class="twitter-share-button" data-url="http://www.careertrucker.com" data-count="horizontal" data-via="careertrucker">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></div>
    
    
<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=198179273566089&amp;xfbml=1"></script><fb:like href="http://www.careertrucker.com" send="true" width="450" show_faces="true" font="arial"></fb:like>

</div>