<div id="footerNav">
        <div class="footerMenu">
                <h1><a href="default.php">home</a></h1>
        </div>
        
         <div class="footerMenu">
                <h1><a href="need-your-cdl-license.php">need your cdl</a></h1>
                <h2><a href="becoming-cdl-driver.php">becoming a cdl driver</a></h2>
                <h2><a href="future-of-trucking.php">future of trucking</a></h2>
                <!--<h2><a href="#">submenu item</a></h2>
                <h2><a href="#">submenu item</a></h2>
                <h2><a href="#">submenu item</a></h2>-->
        </div>
        
        <div class="footerMenu">
                <h1><a href="have-your-cdl-license.php">have a cdl</a></h1>
                <h2><a href="cdl-background-check.php">cdl background check</a></h2>
                <h2><a href="class-a-cdl-vehicles.php">class a cdl vehicles</a></h2>
                <h2><a href="health-conditions.php">health conditions</a></h2>
                <!--<h2><a href="#">submenu item</a></h2>
                <h2><a href="#">submenu item</a></h2>-->
        </div>
        
        <div class="footerMenu">
                <h1><a href="links.php">industry links</a></h1>
                <!--<h2><a href="#">submenu item</a></h2>
                <h2><a href="#">submenu item</a></h2>
                <h2><a href="#">submenu item</a></h2>
                <h2><a href="#">submenu item</a></h2>
                <h2><a href="#">submenu item</a></h2>--> 
        </div>
        
        <div class="footerMenu">
                <h1><a href="contact.php">contact us</a></h1> 
        </div>

    </div>
    
    </div>