	<div id="social">
    	<a href="https://www.facebook.com/pages/Career-Trucker/166336890087327?v=wall" target="_blank"><img border="0" src="images/facebook.gif" /></a>
    	<a href="http://twitter.com/#!/careertrucker" target="_blank"><img border="0" src="images/twitter.gif" /></a>
        <a href="http://www.youtube.com/playlist?p=0E236FC27AA30370" target="_blank"><img border="0" src="images/youtube.gif" /></a>
    </div>