<!-- Begin Social Include -->

<a href="https://www.facebook.com/RoadmasterDriversSchool" target="_blank"><img width="32" height="32" src="/images/facebook.png" alt="Facebook" border="0" /></a>&nbsp;&nbsp;
<a href="http://twitter.com/#!/RoadmasterCDL" target="_blank"><img width="32" height="32" src="/images/twitter.png" alt="Twitter" border="0" /></a>&nbsp;&nbsp;
<a href="http://www.youtube.com/roadmastercdl" target="_blank"><img width="32" height="32" src="/images/youtube.png" alt="YouTube" border="0" /></a>
<!-- End Social Include -->