<div id="contentFooter">

<div style="float:left; width:100px;"><a href="http://twitter.com/share" class="twitter-share-button" data-url="http://www.roadmaster.com" data-text="Roadmaster Drivers School" data-count="horizontal" data-via="RoadmasterCDL">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></div>

<div style="float:left; width:200px;"><a data-pin-do="buttonFollow" href="http://www.pinterest.com/roadmastercdl/">Roadmaster Drivers School</a></div>

<div style="float:left; width:200px;"><div class="g-plusone" data-annotation="inline" data-width="300"></div></div>

<div style="float:left; width:300px;" id="fb-root"><script src="http://connect.facebook.net/en_US/all.js#appId=246328938715243&amp;xfbml=1"></script><fb:like href="http://www.roadmaster.com" send="true" width="450" show_faces="true" font="arial"></fb:like></div>

</div>

<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>