
<div id="footer">

<div id="footerCol1">
<h3>Locations</h3>
	<ul>
		<li><a href="/truck_school_WESTMEMPHIS.php">West Memphis, AR</a></li>
		<li><a href="/truck_school_fontanaCalifornia.php">Fontana, CA</a></li>
		<li><a href="/truck_school_JACKSONVILLE.php">Jacksonville, FL</a></li> 
		<li><a href="/truck_school_ORLANDO.php">Orlando, FL</a></li>
		<li><a href="/truck_school_TAMPA.php">Tampa, FL</a></li>
		<li><a href="/truck_school_INDIANA.php">Indianapolis, IN</a></li>
		<li><a href="/truck_school_northcarolina.php">Dunn, NC</a></li>
		<li><a href="/truck_school_OHIO.php">Columbus, OH</a></li>
		<li><a href="/truck_school_Tulsa.php">Tulsa, OK</a></li>
		<li><a href="/truck_school_Chattanooga_Tennessee.php">Chattanooga, TN</a></li>
		<li><a href="/truck_school_SANANTONIO.php">San Antonio, TX</a></li>
		<li><a href="/truck_school_SaltLake.php">Salt Lake City, UT</a></li>
	</ul>
</div>

<div id="footerCol2">
<ul>
<li><a href="/default.php">Home Page</a></li>
<li><a href="/cdl_training.php">CDL Training</a></li>
<li><a href="/trucking_resources.php"><span>Resources</span></a></li>	
<li><a href="/blog">Blog</a></li>
<li><a href="/contact.php">Apply Now</a></li>
<li><a href="/what-is-cdl-training.php"><span>What is CDL Training</span></a></li>
<li><a href="/what-is-truck-driving-school-like.php"><span>Truck Driving School</span></a></li>
<li><a href="/cdl_training.php"><span>CDL Training at Roadmaster</span></a></li>
<li><a href="/trucking_benefits.php"><span>Truck Driver Benefits</span></a></li>
<li><a href="/refresher_courses.php"><span>CDL Refresher Course</span></a></li>
<li><a href="/terms-of-use.php"><span>Privacy Policy</span></a></li>
</ul>
</div>

<div id="footerCol3">
<ul>
<li><a href="/trucking_about_Roadmaster.php" class="parent">School Info</a></li>
	<ul class="footerSub">
			<li><a href="/trucking_about_Roadmaster-history.php"><span>Roadmaster History</span></a></li>
        	<li><a href="/roadmaster_careers.php"><span>Roadmaster Job Openings</span></a></li>
	</ul>
<li><a href="/truck_school_admissions.php" class="parent"><span>Admission Info</span></a></li>
<li><a href="/truck_school_how-to-apply.php"><span>How to Apply</span></a></li>
<li><a href="/truck_school_finance.php"><span>Finance</span></a></li>	
		<ul class="footerSub">
			<li><a href="/MM/MM-event-listings.php"><span>Event Calendar</span></a></li>
			<li><a href="/trucking_jobs_hiringseminar.php"><span>Recruitment Calendar</span></a></li>
		</ul>
<li><a href="/veteran-cdl-training.php"><span>Veterans Training</span></a></li>       			
<li><a href="/Truck_driving_GraduateLetter.php" class="parent"><span>Graduate Stories</span></a>
		<ul class="footerSub">
			<li><a href="/Truck_driving_Team_Driving.php"><span>Team Driving Stories</span></a></li>
			<li><a href="/truck_school_stories.php"><span>School Stories</span></a></li>
			<li><a href="/truck_school_womandrivers.php"><span>Female Drivers</span></a></li>	
		</ul>

</ul>
</div>



<div id="footerCol4">
<h2 style="text-align:center;">1-800-831-1300</h2>
<div class="footerSocial">

<a href="https://www.facebook.com/RoadmasterDriversSchool" target="_blank"><img width="32" height="32" src="/images/facebook.png" alt="Facebook" border="0" /></a>

<a href="http://twitter.com/#!/RoadmasterCDL" target="_blank"><img width="32" height="32" src="/images/twitter.png" alt="Twitter" border="0" /></a>

<a href="https://plus.google.com/113619994409207860357/posts" target="_blank"><img width="32" height="32" src="/images/gplus-32.png" alt="Google Plus" border="0" /></a>

<a href="http://www.youtube.com/roadmastercdl" target="_blank"><img width="32" height="32" src="/images/youtube.png" alt="YouTube" border="0" /></a>

</div>
</div>


</div>

<!-- Live Chat -->
<!--<script type="text/javascript">
var __lc = {};
__lc.license = 4004091;

(function() {
	var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
	lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>
<script>
var LC_API = LC_API || {};
LC_API.on_chat_started = function()
{
    // track this chat in Google AdWords
    var adwordsID, adwordsLabel, img;

    adwordsID    = "905-507-4970";
    adwordsLabel = "Live Chats";
    img = new Image(1, 1);
    img.src = 'http://www.googleadservices.com/pagead/conversion/'+adwordsID+'/?label='+adwordsLabel+'&script=0';
};
</script>

-->
<!-- END Live Chat -->