<?php include("CPTLib/lead/trackref.php"); trackReferer(); ?>

<!-- Begin Head Include -->

<link href="/inc/css/styles.css" rel="stylesheet" type="text/css" />
<link type="text/css" href="/inc/css/menu.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="/inc/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

<!-- include jQuery library -->
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.1.1.min.js"></script>
<script type="text/javascript" src="/inc/js/jquery.validate.js"></script>
<script type="text/javascript" src="/inc/js/menu.js"></script>
<script type="text/javascript" src="/inc/fancybox/jquery.fancybox-1.3.4.pack.js"></script>

<link type="text/css" href="/inc/css/jquery.foobar.2.1.css" rel="Stylesheet" />
<script type="text/javascript" src="/inc/js/jquery.foobar.2.1.min.js"></script>

<!-- Start FooBar -->
<!--<script type="text/javascript">
  $(function(){
    $foobar({
      "position" : {
        "bar" : "top"
      },
      "display" : {
        "type" : "delayed",
        "delay" : 1000,
        "backgroundColor": "#D12E2E",
        "shadow": true,
        "theme": {
	        "bar": "x-white"
	        }
      },
      "messages": [ 
        "ATTENTION STUDENTS: Roadmaster Tampa is closed tomorrow due to Tropical Storm Isaac",
      ],
    });
  });
</script>-->
<!-- END FooBar -->

<meta property="og:title" content="Roadmaster Drivers School" /> 
<meta property="og:type" content="school" /> 
<meta property="og:url" content="http://www.roadmaster.com" /> 
<meta property="og:image" content="http://www.roadmaster.com/images/RoadmasterLogoMedium.jpg" /> 
<meta property="og:site_name" content="Roadmaster" /> 
<meta property="fb:admins" content="632097602" /> 
<meta name="google-site-verification" content="wJZg8piGi4M7YmmKlzi9r4wCw15ZZTEIGoOxTikJquA" />
<meta itemprop="name" content="Roadmaster Drivers School">
<meta itemprop="description" content="Roadmaster is a hands on truck driving school and CDL training center with locations across the United States.">
<script type="text/javascript">
$(document).ready(function() {

			$("#youtube").fancybox({
				'width'				: '75%',
				'height'			: '75%',
				'autoScale'			: false,
				'transitionIn'		: 'elastic',
				'transitionOut'		: 'elastic',
				'type'				: 'iframe'
			});

		});
	</script>

<!-- End Head Include -->


