<h3 class="headerbar">Locations</h3>
<ul>
    <li><a href="http://www.roadmaster.com/truck_school_WESTMEMPHIS.php">West Memphis, AR</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_fontanaCalifornia.php">Fontana, CA</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_JACKSONVILLE.php">Jacksonville, FL</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_ORLANDO.php">Orlando, FL</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_TAMPA.php">Tampa, FL</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_INDIANA.php">Indianapolis, IN</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_northcarolina.php">Dunn, NC</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_OHIO.php">Columbus, OH</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_Tulsa.php">Tulsa, OK</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_Chattanooga_Tennessee.php">Chattanooga, TN</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_SANANTONIO.php">San Antonio, TX</a></li>
    <li><a href="http://www.roadmaster.com/truck_school_SaltLake.php">Salt Lake City, UT</a></li>
    <li><a href="javascript:;">&nbsp;</a></li>

</ul>