<div id="menu">
    <ul class="menu">
    <li><a href="/default.php"><img border="0" style="padding-top:3px; padding-left:10px;padding-right:10px;" src="/images/RM-Small.png"></a></li>
       <li><a href="/default.php"><span>Home</span></a></li>
       
        <li><a href="javascript:;" class="parent"><span>Locations</span></a>
            <div><ul>
            <li><a href="/truck_school_locations.php"><span>Location Map</span></a></li>
                <li><a href="/truck_school_WESTMEMPHIS.php"><span>West Memphis, AR</span></a></li>
                <li><a href="/truck_school_fontanaCalifornia.php" class="parent"><span>Fontana, CA</span></a>
                <div><ul>
 
        					<li><a href="/truck_school_fontanaCalifornia.php"><span>Buena Park Office</span></a></li>
        					<li><a href="/truck_school_fontanaCalifornia.php"><span>Riverside Office</span></a></li></ul></div></li>
                <li><a href="/truck_school_JACKSONVILLE.php"><span>Jacksonville, FL</span></a></li>
                <li><a href="/truck_school_ORLANDO.php"><span>Orlando, FL</span></a></li>
                <li><a href="/truck_school_TAMPA.php" class="parent" ><span>Tampa, FL</span></a>
                <div><ul>
         					<li><a href="/truck_school_TAMPA.php"><span>Bradenton Office</span></a></li>
        					</ul></div></li>
                <li><a href="/truck_school_INDIANA.php"><span>Indianapolis, IN</span></a></li>
                <li><a href="/truck_school_northcarolina.php" class="parent"><span>Dunn, NC</span></a></li>
			<li><a href="/truck_school_OHIO.php"><span>Columbus, OH</span></a>
			<div><ul>
         					<li><a href="/truck_school_OHIO.php"><span>Springfield Office</span></a></li>
        					</ul></div></li>
			<li><a href="/truck_school_Tulsa.php" class="parent" ><span>Tulsa, OK</span></a></li>

			<li><a href="/truck_school_Chattanooga_Tennessee.php"><span>Chattanooga, TN</span></a></li>
			<li><a href="/truck_school_SaltLake.php"><span>Salt Lake City, UT</span></a></li>
			<li><a href="/truck_school_SANANTONIO.php"><span>San Antonio, TX</span></a></li>
            </ul></div>
        </li>
        
                <li><a href="javascript:;"><span>CDL Training</span></a>
        	<div><ul>
        		 
        		 <li><a href="/what-is-cdl-training.php"><span>What is CDL Training</span></a></li>
        		 <li><a href="/what-is-truck-driving-school-like.php"><span>Truck Driving School</span></a></li>
        		 <li><a href="/cdl_training.php"><span>CDL Training at Roadmaster</span></a></li>
        		 <li><a href="/trucking_benefits.php"><span>Truck Driver Benefits</span></a></li>
        		 <li><a href="/refresher_courses.php"><span>CDL Refresher Course</span></a></li>
        		 
        	</ul></div>
        </li>
        
        <li><a href="javascript:;" class="parent"><span>School Info</span></a>
        <div><ul>
        <li><a href="/trucking_about_Roadmaster.php" class="parent"><span>About Roadmaster</span></a>
        			<div><ul>
        					<li><a href="/trucking_about_Roadmaster-history.php"><span>Roadmaster History</span></a></li>
        					<li><a href="/roadmaster_careers.php"><span>Roadmaster Job Openings</span></a></li>
        					</ul></div>
        
        <li><a href="/truck_school_admissions.php" class="parent"><span>Admission Info</span></a></li>
        <li><a href="/truck_school_how-to-apply.php"><span>How to Apply</span></a></li>
       <li><a href="/truck_school_finance.php"><span>Finance</span></a></li>
        
        <li><a href="/get_hired.php" class="parent"><span>Job Placement</span></a>
        		<div><ul>
        		<li><a href="/MM/MM-event-listings.php"><span>Event Calendar</span></a></li>
				<li><a href="/trucking_jobs_hiringseminar.php"><span>Recruitment Calendar</span></a></li>
        		</ul></div></li>
        		
        <li><a href="/veteran-cdl-training.php"><span>Veterans Training</span></a></li>       			
        				
        				
        			
        			<li><a href="/Truck_driving_GraduateLetter.php" class="parent"><span>Graduate Stories</span></a>
        				<div><ul>
							<li><a href="/Truck_driving_Team_Driving.php"><span>Team Driving Stories</span></a></li>
							<li><a href="/truck_school_stories.php"><span>School Stories</span></a></li>
							<li><a href="/truck_school_womandrivers.php"><span>Female Drivers</span></a></li>	
        				</ul></div>
        			</li>
				
				<li><a href="/trucking_resources.php"><span>Resources</span></a></li>
				
				</ul></div>
        </li>
        

        
        <li><a href="/blog" target="_blank"><span>Blog</span></a></li>
        <li style="background-color:#e02922;"><a href="/contact.php"><span style="color:white;">Apply Now</span></a></li>
        
        <li class="last">
        		<a style="padding: 0 5px;" href="https://www.facebook.com/RoadmasterDriversSchool" target="_blank"><img style="padding-top:10px; padding-left:5px;" width="32" height="32" src="/images/facebook.png" alt="Facebook" border="0" /></a>
			<a style="padding: 0 5px;" href="http://twitter.com/#!/RoadmasterCDL" target="_blank"><img style="padding-top:10px;" width="32" height="32" src="/images/twitter.png" alt="Twitter" border="0" /></a>
						<a style="padding: 0 5px;" href="http://www.google.com/+Roadmaster" target="_blank"><img style="padding-top:10px;" width="32" height="32" src="/images/gplus-32.png" alt="Google Plus" border="0" /></a>
			<a style="padding: 0 5px;" href="https://www.youtube.com/user/RoadmasterCDLSchool" target="_blank"><img style="padding-top:10px;" width="32" height="32" src="/images/youtube.png" alt="YouTube" border="0" /></a>
	   </li>
    </ul>
</div>